name = "MHotkeys"
version = 3
copyright = "CC BY-NC-SA 4.0"
description = "Random hotkeys (filter to highest tech/faction engineer in selection and air related)"
author = "maudlin27"
uid = "mhotkeys-v003-a5cd-ef-qwerty987654"
url = ""
icon = ""
identifier = ""
selectable = true
exclusive = false
ui_only = true
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }