---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by maudlin27.
--- DateTime: 04/10/2026 07:00
---

local SmartSelection = import("/lua/keymap/smartselection.lua")

--Below added when wanted a way to have air units move back to base if no air staging, but doesn't appear to be a way of giving a move order (only aggressivemoveorder via simcallback)
function GetPlayerStartPosition()
    local toCurrentSelection = GetSelectedUnits()
    local tBase
    SmartSelection.smartSelect("AIR FACTORY STRUCTURE")

    local toAirFac = GetSelectedUnits()
    if not(table.empty(toAirFac)) then
        tBase = toAirFac[1]:GetPosition()
    end

    SelectUnits(toCurrentSelection)
    return tBase
end